version: 2
updates:

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      kotlin-plugins:
        patterns:
          - "org.jetbrains.kotlin*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: ".github/actions/checkout-and-configure"
    schedule:
      interval: "weekly"