spring:
  application:
    name: project-radar

  webflux:
    timeout: 120s

  reactor:
    netty:
      http:
        client:
          connection-timeout: 120s

  ai:
    chat:
      client:
        enabled: true # disable auto configuration of chat client

    model:
      chat: openai # openai
      embedding: openai # openai


    openai:
      base-url: https://api.openai.com
#      base-url: http://localhost:1234 # local llm
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
      embedding:
        model: text-embedding-3-small
      http-client:
        connect-timeout: 5m
        read-timeout: 5m

service:
  embedding:
    type: openai # openai, fake

profile:
  reader:
    markdown:
      enabled: true
    pdf:
      enabled: true

projects:
  importer:
    markdown:
      enabled: false
      file: classpath:projects/project-test.md
    pdf:
      enabled: false
      file: classpath:projects/Test.pdf
    platform:
      freelancermap:
        enabled: true
        keywords:
          - java
          - backend
      gulp:
        enabled: false
        keywords:
          - java
          - backend