spring:
  application:
    name: project-radar

  ai:
    chat:
      client:
        enabled: false # disable auto configuration of chat client

    model:
      embedding: openai # openai

    openai:
      base-url: https://api.openai.com
#      base-url: http://localhost:1234 # local llm
      api-key: ${OPENAI_API_KEY}
      embedding:
        model: text-embedding-3-small
      http-client:
        connect-timeout: 60s
        read-timeout: 2m

service:
  embedding:
    type: fake # openai, fake

profile:
  reader:
    markdown:
      enabled: true
    pdf:
      enabled: true

projects:
  importer:
    markdown:
      enabled: true
      file: classpath:projects/project-test.md
    pdf:
      enabled: true
      file: classpath:projects/project-dummy.pdf
    platform:
      freelancermap:
        enabled: false
        keywords:
          - kotlin
          - devops
          - cloud