spring:
  application:
    name: project-radar

  ai:
    chat:
      client:
        enabled: false # disable auto configuration of chat client

    model:
      embedding: openai # openai

    openai:
      base-url: https://api.openai.com
#      base-url: http://localhost:1234 # local llm
      api-key: ${OPENAI_API_KEY}
      embedding:
        model: text-embedding-3-small
      http-client:
        connect-timeout: 60s
        read-timeout: 2m