name: 'Checkout and configure'
description: 'Checkout code and configure environment'

runs:
  using: 'composite'
  steps:
    - name: Checkout latest code
      uses: actions/checkout@v4
      with:
        ref: ${{ env.COMMIT_HASH }}

    - name: Setup java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21

    - name: Setup gradle
      uses: gradle/actions/setup-gradle@v4