name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:
    inputs:
      COMMIT_HASH:
        description: >
          Paste the commit hash here of any commit on any branch or leave
          blank for the latest one on the main branch.
        default: main
        required: false

permissions:
  id-token: write
  pull-requests: write
  contents: write
  issues: read
  checks: write

jobs:
  workflow-gradle-tests:
    name: Tests
    uses: ./.github/workflows/run-tests.yml
    secrets: inherit

  workflow-publish-test-results:
    name: Tests
    needs: [ workflow-gradle-tests ]
    if: ${{ success() || failure() }}
    uses: ./.github/workflows/publish-test-results.yml

  build-application:
    runs-on: ubuntu-latest
    needs: [ workflow-gradle-tests ]
    steps:
      - name: Checkout and configure
        env:
          COMMIT_HASH: ${{ env.COMMIT_HASH }}
        uses: jacq42/project-radar/.github/actions/checkout-and-configure@main

      - name: Build application
        if: false
        run: |
          ./gradlew build -x test