name: Publish test results

on:
  workflow_call:

permissions:
  id-token: write
  pull-requests: write
  contents: write
  issues: read
  checks: write

jobs:
  publish-test-results:
    runs-on: ubuntu-latest
    steps:
      - name: Download test report
        uses: actions/download-artifact@v4
        with:
          path: build/reports/tests

      - name: Generate test report
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: Test Results
          junit_files: ./**/build/test-results/test/TEST-*.xml