name: PITest

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  run-pitest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and configure
        env:
          COMMIT_HASH: ${{ env.COMMIT_HASH }}
        uses: jacq42/project-radar/.github/actions/checkout-and-configure@main

      - name: Run PITest
        run: |
          ./gradlew pitest

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: PITest Mutation Test Report
          path: build/reports/